name: Build and Run Node.js Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t debasishdocker87/nodejs-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push debasishdocker87/nodejs-app:latest

      - name: Run container (optional in CI, usually for testing)
        run: |
          docker run -d -p 3000:3000 --name nodejs-container debasishdocker87/nodejs-app:latest
          sleep 10
          curl http://localhost:3000
          docker stop nodejs-container
          docker rm nodejs-container
